spring.application.name=foroHub
spring.datasource.url=jdbc:postgresql://localhost:5432/forohub
spring.datasource.username=postgres
spring.datasource.password=782311

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
logging.level.org.springframework.security=DEBUG
api.security.secret=mi.clave.secreta.muy.segura.12345